const announces = [
  "Developers are often highly educated, well paid, and young. They’re also skeptical and see through traditional marketing approaches. They share similarities with some of our audiences like Cryptocurrency users, early adopters, and designers, but if the general consensus is that people love to hate advertising, developers take this concept to a new level.",
  "Knowing your audience is the key to marketing. Understanding their pain points, where they go for information, and what kinds of content they appreciate are the first steps to designing a successful advertising campaign.",
  "It’s no surprise that this audience’s impatience carries over to digital advertising. Any marketing tactic that slows down processes or stands in the way of information won’t be well received by this group. This includes popular online ad formats such as pre-roll videos and interstitials, which are more likely to annoy developers than move them through a sales funnel. Complicated or intrusive sign-up forms also apply—it’s wiser for marketers to capture an email and let developers experiment in a test environment, then reach back out if they don’t convert.",
  "No one understands the Internet like developers, which is precisely why they’re so skeptical of today’s digital advertising industry. They’re all too aware of privacy risks through IP and cookie tracking and security threats through insecure and SSL noncompliant ads. These issues are top-of-mind for developers as they see and consider interacting with ads online.",
  "Digital advertising has been unfairly characterized by annoying display ads served through exchange platforms. These ads are often not served in context but are designed to distract users from content.",
  "Like anyone, developers don’t respond well to annoying, tasteless advertising. But unlike most people, developers have the technical know-how to shut out bad advertising by installing ad blockers. They understand that exchange bidding tactics and tracking scripts slow down page load and increase latency on websites. With ad blockers, developers can quickly access publisher content online without robotic, irrelevant ads.",
  "Reaching an audience that’s impatient, suspicious, and advertising-adverse is difficult but not impossible. Advertisers need to leave behind typical marketing tactics and reach developers on their terms through non-intrusive, genuine ads on trusted websites.",
  "Marketers should also ensure ads are clearly relevant to developers. Native ads lose credibility the moment they stop being relevant. Instead of placing ads, picture yourself placing curated content that complements the publisher website.",
  "Marketers can connect with developers by communicating product benefits in ways that developers understand. Advertisers should always be honest with features and perks—remember, developers are inherently suspicious and can see through anything that seems too good to be true.",
  "Advertisers should take advantage of direct advertising opportunities by booking through websites that developers know and trust. Start your search by asking your team of developers which sites they frequent and if they’ve noticed ads they like on those sites.",
  "Another perk of running ads through a publisher network is that the websites cater specifically to their audience’s needs and concerns. For example, publishers on the Carbon network only serve one ad per page in a non-intrusive format. Developers win because they can support publishers that serve non-intrusive ads, allowing them to “pay back” publishers for time spent on quality content. Advertisers also benefit because they have full share of voice on the page and know their ads aren’t annoying the target audience."
];

export default announces;
